path_handler:
  routes:
    routes:
      'fake':
        type: Literal
        options:
          route: /fake
          defaults:
            handler: Fake
      'fakeArrays':
        type: Literal
        options:
          route: /fakeArrays
          defaults:
            handler: FakeArrays
      'fake_classname_test':
        type: Literal
        options:
          route: /fake_classname_test
          defaults:
            handler: FakeClassnameTest
      'fakedef1':
        type: Literal
        options:
          route: /fakedef1
          defaults:
            handler: Fakedef1
      'fakedef2':
        type: Literal
        options:
          route: /fakedef2
          defaults:
            handler: Fakedef2
      'fakedef3':
        type: Literal
        options:
          route: /fakedef3
          defaults:
            handler: Fakedef3
      'pet':
        type: Literal
        options:
          route: /pet
          defaults:
            handler: Pet
        may_terminate: true
        child_routes:
          'findByStatus':
            type: Literal
            options:
              route: /findByStatus
              defaults:
                handler: PetFindByStatus
          'findByTags':
            type: Literal
            options:
              route: /findByTags
              defaults:
                handler: PetFindByTags
          '{petId}':
            type: Segment
            options:
              route: /:petId
              defaults:
                handler: PetPetId
            may_terminate: true
            child_routes:
              'uploadImage':
                type: Literal
                options:
                  route: /uploadImage
                  defaults:
                    handler: PetPetIdUploadImage
      'store':
        type: Literal
        options:
          route: /store
        child_routes:
          'inventory':
            type: Literal
            options:
              route: /inventory
              defaults:
                handler: StoreInventory
          'order':
            type: Literal
            options:
              route: /order
              defaults:
                handler: StoreOrder
            may_terminate: true
            child_routes:
              '{order_id}':
                type: Segment
                options:
                  route: /:order_id
                  defaults:
                    handler: StoreOrderOrderId
      'user':
        type: Literal
        options:
          route: /user
          defaults:
            handler: User
        may_terminate: true
        child_routes:
          'createWithArray':
            type: Literal
            options:
              route: /createWithArray
              defaults:
                handler: UserCreateWithArray
          'createWithList':
            type: Literal
            options:
              route: /createWithList
              defaults:
                handler: UserCreateWithList
          'login':
            type: Literal
            options:
              route: /login
              defaults:
                handler: UserLogin
          'logout':
            type: Literal
            options:
              route: /logout
              defaults:
                handler: UserLogout
          '{username}':
            type: Segment
            options:
              route: /:username
              defaults:
                handler: UserUsername

    default_params:
      middleware: ''
  metadata_cache:
    adapter:
      name: blackhole
#    adapter:
#      name: filesystem
#      options:
#        cache_dir: data/cache/path_handler
#        namespace: ph

  handlers:
    invokables:
      Fake: App\Handler\Fake
      FakeArrays: App\Handler\FakeArrays
      FakeClassnameTest: App\Handler\FakeClassnameTest
      Fakedef1: App\Handler\Fakedef1
      Fakedef2: App\Handler\Fakedef2
      Fakedef3: App\Handler\Fakedef3
      Pet: App\Handler\Pet
      PetFindByStatus: App\Handler\PetFindByStatus
      PetFindByTags: App\Handler\PetFindByTags
      PetPetId: App\Handler\PetPetId
      PetPetIdUploadImage: App\Handler\PetPetIdUploadImage
      StoreInventory: App\Handler\StoreInventory
      StoreOrder: App\Handler\StoreOrder
      StoreOrderOrderId: App\Handler\StoreOrderOrderId
      User: App\Handler\User
      UserCreateWithArray: App\Handler\UserCreateWithArray
      UserCreateWithList: App\Handler\UserCreateWithList
      UserLogin: App\Handler\UserLogin
      UserLogout: App\Handler\UserLogout
      UserUsername: App\Handler\UserUsername
#  consumers:
#  attributes:
#  producers:
