name: Build Test PR 3.0

on:
  push:
    branches: [ "3.0.0" ]

jobs:
  build_push_30:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 17 ]

    steps:
      - uses: actions/checkout@v3
        name: git checkout 3.0.0
        with:
          ref: 3.0.0
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven
      - name: preliminary checks
        run: |
          docker login --username=${{ secrets.DOCKERHUB_SB_USERNAME }} --password=${{ secrets.DOCKERHUB_SB_PASSWORD }}
          set -e
          # fail if templates/generators contain carriage return '\r'
          /bin/bash ./bin/utils/detect_carriage_return.sh
          # fail if generators contain merge conflicts
          /bin/bash ./bin/utils/detect_merge_conflict.sh
          # fail if generators contain tab '\t'
          /bin/bash ./bin/utils/detect_tab_in_java_class.sh
      - uses: s4u/maven-settings-action@v2.8.0
        name: setup maven settings.xml
        with:
          servers: |
            [{
                "id": "sonatype-nexus-staging",
                "username": "${{ secrets.OSSRH_USERNAME }}",
                "password": "${{ secrets.OSSRH_TOKEN }}"
            },
            {
                "id": "sonatype-nexus-snapshots",
                "username": "${{ secrets.OSSRH_USERNAME }}",
                "password": "${{ secrets.OSSRH_TOKEN }}"
            }]
      - name: Build with Maven
        run: |
          # mvn clean install -U -Pdocker -Plinux -DJETTY_TEST_HTTP_PORT=8090 -DJETTY_TEST_STOP_PORT=8089
      - name: Test samples
        if: ${{ matrix.java == 8 }}
        run: |
          mvn -q verify -U -Psamples -Dproject.build.sourceEncoding=UTF8 -Dfile.encoding=UTF8
      - name: docker cli and minimal build and push
        if: ${{ matrix.java == 17 }}
        run: |
          export MY_POM_VERSION=`mvn -q -Dexec.executable="echo" -Dexec.args='${projects.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec`
          echo "POM VERSION" ${MY_POM_VERSION}
          export DOCKER_GENERATOR_IMAGE_NAME=swaggerapi/swagger-generator-v3-minimal
          export DOCKER_CODEGEN_CLI_IMAGE_NAME=swaggerapi/swagger-codegen-cli-v3
          if [[ $MY_POM_VERSION =~ ^.*SNAPSHOT$ ]];
          then
            mvn -DJETTY_TEST_HTTP_PORT=8090 -DJETTY_TEST_STOP_PORT=8089 clean deploy -Pdocker --settings $HOME/.m2/settings.xml
            docker build --rm=false -t $DOCKER_GENERATOR_IMAGE_NAME:unstable -f ./modules/swagger-generator/Dockerfile_minimal ./modules/swagger-generator
            docker tag $DOCKER_GENERATOR_IMAGE_NAME:unstable
            docker push $DOCKER_GENERATOR_IMAGE_NAME:unstable
            docker build --rm=false -t $DOCKER_CODEGEN_CLI_IMAGE_NAME:unstable ./modules/swagger-codegen-cli
            docker tag $DOCKER_CODEGEN_CLI_IMAGE_NAME:unstable
            docker push $DOCKER_CODEGEN_CLI_IMAGE_NAME:unstable
          else
            echo "not building and pushing release docker image: " ${MY_POM_VERSION}
          fi

